spring.application.name=ordemservico
server.port=8081
server.servlet.context-path=/api
# Configuracoes de banco de dados - Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/awos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=public

# swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true

logging.level.org.springframework=INFO
logging.level.com.fasterxml.jackson=DEBUG
logging.level.org.mapstruct=DEBUG