spring.application.name=ordemservico
server.port=8081
server.servlet.context-path=/api
# Configuracoes de banco de dados - Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/awos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=public
